# Site settings
title:       Kuan Butts
email:       kuanbutts@gmail.com
author:      Kuan Butts
description: "Personal web page of Kuan Butts."
baseurl:     ""
url:         "http://kuanbutts.com"

# Google analytics
google_analytics: UA-47292035-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: kuanb
stackoverflow_id: 3407994
twitter_username: buttsmeister
google_plus_id: +KuanButts
linkedin_username: kuanbutts
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
